### ISSUE TITLE
Ошибка при переключении кошельков

### ISSUE THREAD

**Issue by gitKexit** [fintabservice/Bug-tracking#11]
Добрый день!
При переключении кошельков в WEB-версии выдаёт ошибку:

![image](https://user-images.githubusercontent.com/37369517/37642931-fdf3a82a-2c2f-11e8-846a-f860f2e53e3a.png)

**Comment by fintabservice** [comment]
Исправили

**Comment by nikolayozhogov** [comment]
![image](https://user-images.githubusercontent.com/1410130/37644493-dc5c68c6-2c45-11e8-8347-7c4e49bd95d1.png)
Сейчас ошибки нет
