### ISSUE TITLE
Приложение вылетает сразу же после загрузки

### ISSUE THREAD

**Issue by dmitry-yell** [fintabservice/Bug-tracking#12]
Приложение вылетает сразу же после загрузки

ID: 5AB1F9EF2BC8E6BC4B8B45B8

**Comment by nikolayozhogov** [comment]
Укажи пожалуйста версию ios и какой у тебя iphone, это существенно облегчит решение проблемы

**Comment by nikolayozhogov** [comment]
Дополнено пользователем: После добавление первой операции перестало вылетать

**Comment by nikolayozhogov** [comment]
iPhone 6 Plus 10.3.3

**Comment by dmitry-yell** [comment]
Вылетает приложение при запуске, если на сайте создан портфель но не добавлена ни одна из валют. Так же как если пустой портфель просто стоит первым на отображение при загрузке приложения. Стоит удалить пустой портфель или добавить в него транзакцию - приложение загружается.

iPhone 6 Plus
iOS 10.3.3

**Comment by fintabservice** [comment]
В процессе
