### ISSUE TITLE
При обновлении главного экрана в приложении прыгает индикатор обновления 

### ISSUE THREAD

**Issue by dmitry-yell** [fintabservice/Bug-tracking#13]
При обновлении данных в приложении индикатор обновления наезжает на элементы 

![6](https://user-images.githubusercontent.com/37412224/37702428-8ed1f198-2d03-11e8-958d-dd012a78662d.PNG)

iPhone 6 Plus 10.3.3

**Comment by nikolayozhogov** [comment]
Передал программисту

**Comment by fintabservice** [comment]
Воспроизвести ошибку нам так и не удалось :(
Рекомендация: обновить ОС
