### ISSUE TITLE
Не пересчитывает портфель после добавления\изменения транзакции

### ISSUE THREAD

**Issue by sshevelev** [fintabservice/Bug-tracking#15]
1. Общее описание проблемы.
Не пересчитывается портфель после добавления\изменения транзакции в web-версии.
2.Что было сделано:
Добавил транзакцию по покупке за 0.00349125 BTC (это размер остатка этой валюты) 50 ETH на бирже Биттрекс
Переключился на вкладку http://test-dev.fintab.io/dashboard
3.Ожидаемый результат:
в портфеле нет BTC. В портфеле есть 50 ETH.
4. Полученный результат:
Обновилась оценка в USD согласно 50 ETH
В портфеле всё так же есть BTC, но нет 50 ETH
Обновляется портфель только из меню - "Обновить расчёты"

В Android-версии при добавлении транзакции даже баланс не обновляется. Приходится лезть в веб-версию и вызывать "Обновить расчёты".

**Comment by nikolayozhogov** [comment]
Мы поправили проблему, попробуй обновить кеш в веб-версии)
и только после этого тестировать
