### ISSUE TITLE
Пропала транзакция

### ISSUE THREAD

**Issue by sshevelev** [fintabservice/Bug-tracking#16]
Портфель:
ID: 5AAA88702BC8E6875D8B468C
Не могу найти в списке транзакцию, которую ввёл последней (от 01.12.2017). Транзакция не показывается даже если кнопка "Показать ещё" уже исчезла и как-бы все транзакции видно.
Подробности транзакции:
Приобретение 0,0015585 btc за рубли. 
Планировал ввести что взято было по курсу 1 млн. рубл. А ввёл случайно, что было куплено за 1 млн. рублей. 
В результате в балансе вижу, что вложил более 19 тысяч $ , чего по операциям не видно.... 

Удалил в скопированном портфеле все операции обмена. Оставил только добавление (все они у меня от 01.12.2017) - сразу появилась косячная операция и я смог его поправить (ID: 5AB4B6FE2BC8E6F3608B4679 )
--

**Comment by nikolayozhogov** [comment]
Очень странный случай, разберем.

**Comment by sshevelev** [comment]
Создал копию портфеля одну. Там не было. 
Создал вторую копию - там нашёл её сразу, исправил.... )
