### ISSUE TITLE
Не отображается добавление токена

### ISSUE THREAD

**Issue by dmitry-yell** [fintabservice/Bug-tracking#17]
На сайте, при добавлении токена BM* (Bitcomo) транзакция появляется в списке добавленных. Но После переключения на главную страницу со списком валют ее там нет, так же как в списке последних транзакций. Если снова нажать на добавление валюты и добавить, то она отобразиться ниже, вместе с добавленной ранее и так же обе не будут видны при переключении на главную страницу. (Причем после третьей попытке иконка изменилась))

![2018-03-28_17-06-05](https://user-images.githubusercontent.com/37412224/38034402-e186afb2-32aa-11e8-88c5-19a63d36f99e.png)
![2018-03-28_17-06-39](https://user-images.githubusercontent.com/37412224/38034406-e37815ae-32aa-11e8-879e-c18d27532711.png)

ID: 5ABB9CDE2BC8E602548B45C8

**Comment by nikolayozhogov** [comment]
Это связано с кешированием, в процессе решения проблемы

**Comment by fintabservice** [comment]
Пофиксили
