### ISSUE TITLE
Вылетает приложение при запуске 

### ISSUE THREAD

**Issue by dmitry-yell** [fintabservice/Bug-tracking#18]
Вылетает приложение при запуске, если на сайте создан портфель но не добавлена ни одна из валют. Так же как если пустой портфель просто стоит первым на отображение при загрузке приложения. Стоит удалить пустой портфель или добавить в него транзакцию - приложение загружается.

iPhone 6 Plus 
iOS 10.3.3

**Comment by fintabservice** [comment]
В процессе

**Comment by golovan2** [comment]
Аналогично
iPhone 5C, iOS 10.3.3

**Comment by fintabservice** [comment]
Исправили
