### ISSUE TITLE
В приложении не пропала удаленная валюта

### ISSUE THREAD

**Issue by dmitry-yell** [fintabservice/Bug-tracking#19]
После удаления в приложении, в разделе  "транзакции" операции ввода валюты, в разделе "портфель" все равно осталась эта позиция. На сайте валюта пропала. 

![img_1944](https://user-images.githubusercontent.com/37412224/38525303-6892bbd2-3c5a-11e8-944c-97d1c4cdd554.PNG)
![img_1945](https://user-images.githubusercontent.com/37412224/38525305-68b1ae3e-3c5a-11e8-9cc6-5fda6e5f76dd.PNG)

ID: 5AB23D3B2BC8E671608B45E9
iPhone 6 Plus
iOS 10.3.3

**Comment by fintabservice** [comment]
Это связано с кешированием данных, мы занимаемся данным вопросом.

**Comment by fintabservice** [comment]
Пофиксили
