### ISSUE TITLE
Ошибка при импорте файла CSV

### ISSUE THREAD

**Issue by dmitry-yell** [fintabservice/Bug-tracking#20]
После добавления файла и нажатия кнопки "завершить импорт" появляется это

![213132](https://user-images.githubusercontent.com/37412224/38769458-4f55a412-400c-11e8-986d-e3c535863a32.JPG)
Сделки экспортированы из сервиса cointracking в файл csv

Файл csv с депозитами и выводами экспортированный из бинанс так же не подходит. Пишет - wrong file type
Файлы xlsx с историей сделок из бинанс то же не ест

ID: 5AABBF092BC8E621098B4635
Google Chrome Версия 65.0.3325.181 (Официальная сборка), (64 бит)

**Comment by fintabservice** [comment]
На странице "Импорт CSV" написана инструкция по импорту. Вам необходимо сопоставить колонки определенным образом и загружать файлы только с расширением CSV.

**Comment by dmitry-yell** [comment]
Не работает. Пишет ошибку.
"Обнаружены ошибки в следующих строках:
FATAL: Некорректный тип транзакции"

Недостаточно колонок, комментариев может быть больше. Нельзя выбрать две колонки под комментарий. Название просто "количество" надо поменять на "проданное количество" тогда уж.

**Comment by fintabservice** [comment]
В процессе исправления
