### ISSUE TITLE
Ошибки на вкладке последние транзакции

### ISSUE THREAD

**Issue by sshevelev** [fintabservice/Bug-tracking#21]
Notice: Undefined index: is_admin in /srv/www/dev/root/app/view/include/transactions-table.php on line 19
Notice: Undefined index: is_admin in /srv/www/dev/root/app/view/include/transactions-table.php on line 203
Notice: Undefined index: is_admin in /srv/www/dev/root/app/view/include/transactions-table.php on line 203
Notice: Undefined index: is_admin in /srv/www/dev/root/app/view/include/transactions-table.php on line 203
Notice: Undefined index: is_admin in /srv/www/dev/root/app/view/include/transactions-table.php on line 203
Notice: Undefined index: is_admin in /srv/www/dev/root/app/view/include/transactions-table.php on line 203

http://take.ms/6aUaF

Во всех портфелях.
ID: 5AB4B9E12BC8E6495F8B4649 - для примера.

**Comment by fintabservice** [comment]
Это иногда еще будет появляться на dev, но на beta такого не появится больше.
