### ISSUE TITLE
Ошибка при подключении API Binance

### ISSUE THREAD

**Issue by dmitry-yell** [fintabservice/Bug-tracking#22]
Ошибка при подключении API Binance, и портфель отображается с именем "MY", хотя у меня называется "API"

![432243243423](https://user-images.githubusercontent.com/37412224/38879625-75fc9e56-426c-11e8-9ced-08418293e4d1.JPG)
![65436543654343](https://user-images.githubusercontent.com/37412224/38879626-7634dbe0-426c-11e8-9a41-095db08c300d.JPG)

ID: 5AD4E6AF2BC8E63D1F8B45AC

**Comment by fintabservice** [comment]
По умолчанию у бинанс создается ключ для торгов, а не для получения информации.
1) Проверьте ваш ключ.
2) Проверьте что портфель, в который вы хотите выгружать транзакции существует.

**Comment by fintabservice** [comment]
Мы исправили проблему с названием портфеля, а вот если красным написана ошибка импорта - значит либо ключи не правильные, либо на ключи не распространяются права отдавать транзакции
