### ISSUE TITLE
Недоступно добавление транзакций

### ISSUE THREAD

**Issue by sshevelev** [fintabservice/Bug-tracking#23]
Всего 2 портфеля в профиле - и запрет на ввод транзакций - типа добавление транзакций доступно только в первых двух портфелях на FREE тарифе.
ID: 5AB4B9E12BC8E6495F8B4649 - первый портфель
ID: 5AB9BF6E2BC8E6715F8B4797 - второй.
Кнопка добавить транзакцию отключена.

**Comment by fintabservice** [comment]
Только в первые 2 портфеля можно добавлять транзакции на Free-тарифе

**Comment by sshevelev** [comment]
Ну так это и были единственно оставшиеся портфели... их ровно 2.
Возможно алгоритм учитывает удалённые портфели и получается ситуация, когда просто все портфели становятся только для чтения.
