### ISSUE TITLE
Ошибка расчёта прибыли с транзакции

### ISSUE THREAD

**Issue by sshevelev** [fintabservice/Bug-tracking#26]
1. Общее описание проблемы.
Неправильно отображается Прибыль по транзакции.
2. Что было сделано:
Ввёл транзакцию обмена битка на доллар. Биржа Биттрекс. 
Продал 0.0214 BTC за 201$.
3. Ожидаемый результат:
Чёткой формулы расчёта вашей не вижу, но явно не  939396.43%
Полученный результат:
![dashboard _ fintab - google chrome 2018-05-23 15 22 37](https://user-images.githubusercontent.com/1333752/40412324-386ceefe-5e9d-11e8-82aa-cfcba6909a8c.png)
Портфель:
ID: 5AB4B9E12BC8E6495F8B4649

**Comment by fintabservice** [comment]
Исправили
