### ISSUE TITLE
Отсутствие точки на клавиатуре

### ISSUE THREAD

**Issue by golovan2** [fintabservice/Bug-tracking#3]
1. Общее описание проблемы:
Невозможность сохранить количество и стоимость криптовалюты
2. Что было сделано:
Добавление либо изменение транзакции - после вписывания количества криптовалюты и её стоимости результат сохраняется с нулями (0)
3. Ожидаемый результат:
Добавление транзакции с правильным отображением количества и цены криптовалюты
4. Полученный результат:
Транзакция добавилась с количеством криптовалюты 0.0 и ценой 0.0

Это связано с тем, что количество и стоимость криптовалюты нужно вводить с точкой (пример 140.42754672), однако на клавиатуре есть только запятая, из-за этого результат не сохраняется и стоят нули.
![photo_2018-03-15_14-18-04](https://user-images.githubusercontent.com/15311682/37466600-7149472e-285e-11e8-84fd-30f0d4ec9346.jpg)

**Comment by nikolayozhogov** [comment]
Да, действительно ошибка есть, поставил задачу iOS программисту

**Comment by golovan2** [comment]
iPhone 5C, iOS 10.3.3
