### ISSUE TITLE
Ошибка при удалении транзакции (api method not found)

### ISSUE THREAD

**Issue by golovan2** [fintabservice/Bug-tracking#4]
1. Общее описание проблемы:
Невозможность удалить транзакцию
2. Что было сделано:
Удерживание транзакции - (Вы уверены, что хотите удалить транзакцию?) Да
3. Ожидаемый результат:
Транзакция удаляется
4. Полученный результат:
Появление на экране ошибки "api method not found"

![photo_2018-03-15_14-42-43](https://user-images.githubusercontent.com/15311682/37466868-1f5f02cc-285f-11e8-96f5-433f41783787.jpg)

**Comment by nikolayozhogov** [comment]
Исправили
