### ISSUE TITLE
Не отображаются данные по бирже 1BTCXE

### ISSUE THREAD

**Issue by dmitry-yell** [fintabservice/Bug-tracking#6]
В списке бирж отсутствуют данные по бирже 1BTCXE

Добавил две операции, указав биржу 1BTCXE, на главной странице в списке бирж данные по этой бирже не появились.

![1](https://user-images.githubusercontent.com/37412224/37475963-fab2afac-2884-11e8-91a1-273bcbfc45ae.JPG)

ID: 5AA98A8F2BC8E6CF138B459D

**Comment by fintabservice** [comment]
#7
