### ISSUE TITLE
Не отображаются данные по бирже Binance 

### ISSUE THREAD

**Issue by dmitry-yell** [fintabservice/Bug-tracking#7]
В списке бирж отсутствуют данные по бирже Binance

Добавил несколько операций, указав биржу Binance, на главной странице в списке бирж данные по этой бирже не появились.

![2](https://user-images.githubusercontent.com/37412224/37476351-00e4c530-2886-11e8-8a37-9f15fc6cac28.JPG)

ID: 5AA98A8F2BC8E6CF138B459D

**Comment by nikolayozhogov** [comment]
Скопировал ваш портфель себе, биржа Binance в списке появилась:

![image](https://user-images.githubusercontent.com/1410130/37583679-2db1c748-2b74-11e8-8625-e7dc3849ea3c.png)

В списке бирж мы не показываем биржи, если баланс на них будет отрицательный. Это можно проверить - нажав на биржу (в вашем случае Binance) в списке транзакций. Вы перейдете на страницу биржи и увидите сколько средств на ней:

![image](https://user-images.githubusercontent.com/1410130/37583736-5f662bf8-2b74-11e8-953a-f0d3da830c4f.png)

**Comment by dmitry-yell** [comment]
Я скопировал портфель у себя, ничего не появилось. Делал очистку кеша и жесткую перезагрузку, естественно жал на кнопку для обновления расчетов) Баланс на бирже заметно положительный)

**Comment by dmitry-yell** [comment]
На новом портфеле то же самое

![5](https://user-images.githubusercontent.com/37412224/37697595-b223a930-2cee-11e8-867d-146c854650bd.JPG)

ID: 5AB1F9EF2BC8E6BC4B8B45B8

**Comment by dmitry-yell** [comment]
На новом портфеле вроде бы все в порядке
