### ISSUE TITLE
При импорте CSV файла не отображается надпись на желтой кнопке внизу

### ISSUE THREAD

**Issue by dmitry-yell** [fintabservice/Bug-tracking#9]
В разделе для импорта файла CSV
При импорте CSV файла, после его загрузки, не отображается надпись на желтой кнопке внизу

![4](https://user-images.githubusercontent.com/37412224/37522150-1e4c75ba-2934-11e8-85e0-615f6ebf2eb0.JPG)

**Comment by nikolayozhogov** [comment]
Исправлено
![image](https://user-images.githubusercontent.com/1410130/37585686-c55f22dc-2b7b-11e8-9eff-52111b115dec.png)
